[package]
name = "bitcoin-script-decode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]
# bitcoin = "0.27.0"
# bitcoin_hashes = "0.12.0"

[dependencies]
bitcoin = "0.28.2"
hex = "0.4.3"
